; Sections can be named anything, and you can have more than one - sections that appear first in the document are prioritized
[ollama]
; Backend, either "openai" or "ollama"
backend=ollama
; LLM model, may be omitted for OpenAI backends
model=llama3.1:8b
; RAG embedding model, may be omitted for OpenAI backends
embedding_model=llama3.1:8b
; URL that hosts the OpenAI/Ollama API - defaults to localhost:11434 for Ollama and OpenAI's URL for OpenAI
base_url=http://10.0.0.128:11434
; API key, currently only used for OpenAI backends
api_key=<insert your API key here>
; Sampling temperature, defaults to 0
temperature=0


